### ISSUE TITLE
Php postgresql driver is also needed

### ISSUE THREAD

**Issue by seljukgulcan** [teddybee-r/GwentOneDB#1]
I got `PHP Fatal error:  Uncaught PDOException: could not find driver in  ...` error when I selected the first option. I needed to run the following commands to get rid of the error.

```
sudo apt install php7.2-pgsql
sudo phpenmod pdo_pgsql
sudo systemctl restart postgres
```

I don't know if it's just related to my setup. If it's not you may want to mention it in the requirement section.

Cool repo btw. I'm glad to find an up-to-date card resource.

**Comment by teddybee-r** [comment]
True I forgot about that.
My setup comes from an ansible playbook with tons of php addons included - mainly the ones symfony wants.

README updated - also with the API option
